swanhub, swanspawner: New feature for notebook arguments
swan-cern/jupyterhub-extensions pull request #109
Opened 2024-07-16 12:51 UTC by RodrigoSobral2000

Spawner can now use GET for getting the same arguments it gets through POST requests. With this, an URL that includes a `notebook` argument can open it after launching a session with the remaining specified parameters. If it is a customenv session, it just forwards the `notebook` argument to the SwanCustomEnvironments extension and this will take care of the rest.

2024-07-16 19:56 UTC, diocas reviewed
So... I have opinions...

I don't know what was discussed with @etejedor , but why are we setting this logic in the backend and not in the frontend? (here we go again, always frontend.. I know..)

My big issue with this is that we are adding logic to the spawn handler when we should be removing it and stop wrapping jupyterhub.

I suppose the reason to add it to the backend was to make the startup automatic. If it was in the frontend, users get the options automatically selected, but can still do changes before starting the session. Also, they can see what are the options that are being selected.
For example, with the current implementation, I can create a short link to SWAN, with a user script parameter pointing to a script in my home, that fetches the oauth token of the users. If someone clicks on it, this would start automatically without having time to check if it is safe.
Also, until we do backend checks of the options (that we should do), this makes it easier for users to try non-accepted options.

If we still want to make the startup automatic, I would check first if we can interact with the spawner from a service (I think we can't, but I would check it first). If we can, we could expose a new endpoint that gets the parameters and starts the session. It can even have a confirmation dialogue asking the user if they trust the options.

2024-07-16 19:56 UTC, diocas commented on SwanHub/swanhub/spawn_handler.py
> +                configs.software_source: query_options.get(configs.software_source, [b'']),
Why are defaults arrays of bytes?

2024-07-16 19:56 UTC, diocas commented on SwanSpawner/swanspawner/swanspawner.py
> +                raise ValueError('Invalid notebook path: %s' % options[self.notebook])
f-strings is better.

2024-07-19 08:19 UTC, RodrigoSobral2000 commented on SwanSpawner/swanspawner/swanspawner.py
> +            options[self.notebook]                  = formdata.get(self.notebook, [''])[0]
The `None` value will be propagated to the script and it will be read as a normal string. If empty, it gets easier for the script to check if the its value is empty.

2024-07-19 10:17 UTC, diocas requested changes

2024-07-19 10:17 UTC, diocas commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +    <!-- Notebook path information text -->
Not a fan, as you know :) We can wait to see what @etejedor thinks.

2024-07-19 10:17 UTC, diocas commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +        var notebook_config = document.getElementById('notebook_config');
Not sure if `notebook_config` conveys the real meaning of this var/text box. It's just the notebook url, right?

2024-07-19 10:17 UTC, diocas commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +        const is_software_source_valid = ["lcg", "customenv"].includes(software_source);
Take `sourceConfig` out of the function where is defined, and put it in the parent scope so that you can use it here as the list of valid sources. Otherwise you have 2 lists that need to be kept in sync.

2024-07-19 10:17 UTC, diocas commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +            const use_jupyterlab = (urlParams.get('use-jupyterlab') || "").toLowerCase() === 'true';
Not really a choice if you redirect users to lab when they provide a notebook path.

2024-07-19 10:17 UTC, diocas commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +        if (is_software_source_valid) {
Should we show an error?

2024-07-19 10:17 UTC, diocas commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +                const selected_lcg = urlParams.get('LCG-rel') || select_default_option("lcgReleaseOptions");
Do you really need to have so many similar lines? I would try to use a for-loop (as discussed), and you could even get the parameters directly from url params without having to define them here. I mean, a dynamic thing, so that I can add a form field called cenasOptions, and to set its value, I would just need to provide a query param called "cenas", without ever touching this code here.

2024-07-19 10:17 UTC, diocas commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +                customenvOption.disabled = true;
This is not very future-proof. If I need to create a different form section, I would have to set both as disabled. Doing the opposite, making the default disabled and enabling it on selection, would make it easier.

2024-07-19 12:37 UTC, RodrigoSobral2000 commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +        var notebook_config = document.getElementById('notebook_config');
More than just that, it includes the label, `more...` details and the input with the notebook value itself

2024-07-19 12:38 UTC, RodrigoSobral2000 commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +        var notebook_config = document.getElementById('notebook_config');
I tried to follow the same pattern as the ones above

2024-07-22 13:41 UTC, diocas requested changes
Just some small suggestions and we're good to go.

2024-07-22 13:41 UTC, diocas commented on SwanHub/swanhub/spawn_handler.py
> +        # the software_source query argument to re-render the form and fulfill
```suggestion
        # the software_source query argument to re-render the form and fill
```

2024-07-22 13:41 UTC, diocas commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +    function select_default_option(id) {
```suggestion
    function get_default_option(id) {
```

2024-07-22 13:41 UTC, diocas commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +     * Fulfill the given input with the specified value
```suggestion
     * Set the given input with the specified value
```

2024-07-22 13:41 UTC, diocas commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +    function select_input(id, value) {
```suggestion
    function set_input(id, value) {
```

2024-07-22 13:41 UTC, diocas commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +    function select_options(elements) {
```suggestion
    function set_options(elements) {
```

2024-07-22 13:41 UTC, diocas commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +    function select_checkbox(id, checked) {
```suggestion
    function set_checkbox(id, checked) {
```

2024-07-22 13:41 UTC, diocas commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +            const error_message = document.createElement('span');
Can we make the error build a function?

2024-07-22 13:41 UTC, diocas commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +            error_message.appendChild(document.createElement('br'));
why a br?

2024-07-22 13:41 UTC, diocas commented on SwanSpawner/swanspawner/templates/options_form_template.html
> -            adjust_spark();
no need to adjust spark?

2024-07-22 13:44 UTC, diocas commented on SwanSpawner/swanspawner/swanspawner.py
> +            options[self.notebook]                  = formdata.get(self.notebook, '')[0]
Since we allow any file, "notebook" might be a bit misleading.

2024-07-22 14:10 UTC, RodrigoSobral2000 commented on SwanSpawner/swanspawner/templates/options_form_template.html
> -            adjust_spark();
From what I understand, `adjust_spark` was renamed to `adjust_options`, and it is being called at line 330 in order to update its options according to the freshly set lcg/platform

2024-07-22 14:11 UTC, RodrigoSobral2000 commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +            error_message.appendChild(document.createElement('br'));
To create a separation between the message error and the header message

2024-08-05 16:00 UTC, etejedor commented on SwanSpawner/swanspawner/swanspawner.py
> +            options[self.file]                  = formdata.get(self.file, '')[0]
Can you align the `=` with the others?

2024-08-05 16:05 UTC, etejedor commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +
Do these changes have to do with launch arguments? If not, separate PR please, one commit per purpose.

2024-08-05 16:07 UTC, etejedor commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +        <span class='nb'>JupyterLab is the latest web-based interactive development environment for files, code and data. More information <a target="_blank" href="https://jupyterlab.readthedocs.io/e
Please do not change this, it comes literally from the JupyterLab website.

2024-08-05 16:08 UTC, etejedor commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +                    <span class='nb'>Name of the Spark cluster to connect to from files. See the <a target="_blank" href="https://hadoop-user-guide.web.cern.ch/">Hadoop User guide</a> and the <a targ
Also do not change this, we connect to the Spark clusters from notebooks.

2024-08-05 16:09 UTC, etejedor commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +                <span class='nb'>Relative path to the file to be opened after the session is launched. For EOS repositories, it's relative to CERNBOX_HOME, for Git repositories, it's relative to the
```suggestion
                <span class='nb'>Relative path of the file to be opened after the session is launched. For EOS repositories, it is relative to CERNBOX_HOME; for Git repositories, it is relative to the repository root.</span>
```

2024-08-05 16:15 UTC, etejedor commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +        } else if (software_source && !is_software_source_valid) {
The second condition (`!is_software_source_valid`) is always true here, since you are the `else` of `if (is_software_source_valid)`. Therefore, no need to check it.

Regarding the first condition (`software_source`), can we just not check it and print whatever we have, even if empty? Otherwise we won't get an error message if `software_source` is empty.

In summary, this can become a single `} else {`.

2024-08-05 16:17 UTC, etejedor commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +    function adjust_repo_typeOptions() {
Snake and camel case combined in a function name? Not nice...

Proposal, even if long: `adjust_repository_type_options()`.

2024-08-06 07:18 UTC, RodrigoSobral2000 commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +
Yes, in a way. I moved it to a bigger scope to resuse it for filling the form automatically

2024-08-06 11:26 UTC, etejedor commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +
Ok then.

2024-08-06 11:29 UTC, etejedor approved these changes

2024-08-06 11:35 UTC, merged