check JWT token signature and use PyJWT 2 (fixes #31 #32)
swan-cern/jupyterhub-extensions pull request #34
Opened 2021-03-15 06:55 UTC by rccern

2021-03-15 07:29 UTC, diocas requested changes
Just some quick changes and a question. Thanks

2021-03-15 07:29 UTC, diocas commented on KeyCloakAuthenticator/keycloakauthenticator/auth.py
> +    def _decode_token(self, token, options={}):
I propose we remove the call to this method from `get_roles_for_token`, and put it in `authenticate`. If decoding fails, you return a 403. If not, you take the decoded token, and pass it to `get_roles_for_token`.

2021-03-15 07:29 UTC, diocas commented on KeyCloakAuthenticator/keycloakauthenticator/auth.py
> +            decoded_refresh_token = self._decode_token(auth_state['refresh_token'],options={"verify_signature": False})
If the `refresh_token` has expiration, does the decoding work or should we also set `verify_exp False`?

2021-03-15 07:29 UTC, diocas commented on KeyCloakAuthenticator/keycloakauthenticator/auth.py
> +            decoded_refresh_token = self._decode_token(auth_state['refresh_token'],options={"verify_signature": False})
(add a space in between `decoded_access_token =self._decode_token` and  `['access_token'],options`.

2021-03-15 07:29 UTC, diocas commented on KeyCloakAuthenticator/keycloakauthenticator/auth.py
> +                        self.log.info('aquired public key from %s  ' % jwks_uri)
`'Aquired public key from %s'`

2021-03-15 08:34 UTC, rccern commented on KeyCloakAuthenticator/keycloakauthenticator/auth.py
> +            decoded_refresh_token = self._decode_token(auth_state['refresh_token'],options={"verify_signature": False})
i checked and the refresh tokens have no expiration

2021-03-15 10:04 UTC, rccern commented on KeyCloakAuthenticator/keycloakauthenticator/auth.py
> +    def _decode_token(self, token, options={}):
if we do this, we need to change to the jhub config, because we do 
`spawner.user_roles = authenticator.get_roles_for_token(auth_state['access_token'])` now

2021-03-15 14:56 UTC, diocas commented on KeyCloakAuthenticator/keycloakauthenticator/auth.py
> +            decoded_refresh_token = self._decode_token(auth_state['refresh_token'],options={"verify_signature": False})
Read my comment bellow:
` # If we request the offline_access scope, our refresh token won't have expiration`

So, it can have expiration.

2021-03-15 14:56 UTC, diocas commented on KeyCloakAuthenticator/keycloakauthenticator/auth.py
> +                        self.log.info('aquired public key from %s  ' % jwks_uri)
This was not fixed.

2021-03-15 15:00 UTC, rccern commented on KeyCloakAuthenticator/keycloakauthenticator/auth.py
> +            decoded_refresh_token = self._decode_token(auth_state['refresh_token'],options={"verify_signature": False})
but how do you know if they have the offline_access scope if you don't decode them?

2021-03-15 15:05 UTC, diocas commented on KeyCloakAuthenticator/keycloakauthenticator/auth.py
> +            decoded_refresh_token = self._decode_token(auth_state['refresh_token'],options={"verify_signature": False})
Why do we care? You just need to be sure that we have `{"verify_exp": False}` just like in the previous line. Btw, this option should be False by default, correct? So in the previous line we should also not need it?

2021-03-18 09:53 UTC, diocas commented on KeyCloakAuthenticator/keycloakauthenticator/auth.py
> +                        self.public_key = RSAAlgorithm(RSAAlgorithm.SHA256).from_jwk(jwk_data['keys'][0])
I have a doubt here: is this generic? Since we are setting the signing algorithms, I'm not sure this will also influence.. To be seen in the future if someone complains.

2021-03-18 09:54 UTC, diocas commented on KeyCloakAuthenticator/keycloakauthenticator/auth.py
>              # If we request the offline_access scope, our refresh token won't have expiration
I also have a doubt whether we should check the token after the refresh...

2021-03-18 09:56 UTC, rccern commented on KeyCloakAuthenticator/keycloakauthenticator/auth.py
>              # If we request the offline_access scope, our refresh token won't have expiration
this check is not related to this change, no?  if we check every token we decode (except the refresh token, which we can't check), we are fine

2021-03-18 16:34 UTC, diocas commented on KeyCloakAuthenticator/keycloakauthenticator/auth.py
>              # If we request the offline_access scope, our refresh token won't have expiration
But we do not decode the token after getting the refreshed one. That's my point.

2021-03-24 07:53 UTC, rccern commented on KeyCloakAuthenticator/keycloakauthenticator/auth.py
>              # If we request the offline_access scope, our refresh token won't have expiration
ok now i'm  calling decode_token(access_token) after the refresh

2021-03-25 07:49 UTC, diocas approved these changes

2021-03-25 07:51 UTC, merged