Swanhub041
swan-cern/jupyterhub-extensions pull request #46
Opened 2021-09-14 15:07 UTC by rccern

Readding an `await` that I had removed by mistake

Removing the #changeconfig query param because we don't have swanrc anymore

2021-09-14 19:14 UTC, diocas requested changes
You want (/need) to remove `changeconfig` from the **spawn** handler. You don't want to remove it from the **home** handler. Otherwise there's no way you can shutdown a session.

So this PR should touch only `sparn_handler` and `handlers_configs` and you need to change the url in the home.html (`window.location.replace('{{base_url}}spawn?changeconfig');`) and that's it.

2021-09-14 19:14 UTC, diocas commented on SwanHub/swanhub/templates/home.html
> -{% else %}
This should not be removed! Otherwise there is no way to change the user session.

2021-09-15 06:22 UTC, rccern commented
Thanks, I fixed the issues

2021-09-15 15:48 UTC, diocas approved these changes

2021-09-15 15:48 UTC, merged