WIP Notifications
swan-cern/jupyterhub-extensions pull request #62
Opened 2022-03-08 13:28 UTC by rccern

still missing the Dockerfile

2022-03-09 07:15 UTC, rccern commented
added the dockerfile

2022-03-09 07:41 UTC, krishnan-r commented on SwanNotificationsService/Dockerfile
> +RUN pip install swannotificationsservice
```suggestion
RUN pip install --no-cache-dir swannotificationsservice
```

2022-03-09 07:56 UTC, krishnan-r commented on SwanNotificationsService/swannotificationsservice/service.py
> +        user_pod = self.v1.read_namespaced_pod(f'jupyter-{username}', self.namespace)
should we wrap this in `IOLoop.current().run_in_executor` as it blocks the thread for all other requests [as described here](https://www.tornadoweb.org/en/stable/faq.html#why-isn-t-this-example-with-time-sleep-running-in-parallel). It would not be noticable until we have many many users though

2022-03-09 08:14 UTC, diocas requested changes

2022-03-09 08:14 UTC, diocas commented on SwanNotificationsService/Dockerfile
> +FROM gitlab-registry.cern.ch/linuxsupport/cs9-base:20220301-1.x86_64
I don't think we need anything special from centos (at least not at this time). So I would use the smallest image with Py3 available instead.

2022-03-09 08:14 UTC, diocas commented on SwanNotificationsService/swannotificationsservice/app.py
> +            (r'.*', SwanNotificationsService,
Why do we need this wildcard?

2022-03-09 08:14 UTC, diocas commented on SwanNotificationsService/swannotificationsservice/service.py
> +        user_pod = self.v1.read_namespaced_pod(f'jupyter-{username}', self.namespace)
Careful, this is not compatible with named servers. Can we just add a query parameter to specify a named server?
This also assumes our pods are called `jupyter-xxx`, which is the case, but this is actually configurable.

2022-03-09 08:14 UTC, diocas commented on SwanNotificationsService/swannotificationsservice/service.py
> +        if self.v1.read_node(user_node).spec.unschedulable:
Out of curiosity, how do you define a non schedulable node?

2022-03-09 08:39 UTC, rccern commented on SwanNotificationsService/Dockerfile
> +FROM gitlab-registry.cern.ch/linuxsupport/cs9-base:20220301-1.x86_64
ok, please let me know which image you want to use

2022-03-09 08:41 UTC, rccern commented on SwanNotificationsService/swannotificationsservice/service.py
> +        if self.v1.read_node(user_node).spec.unschedulable:
`kubectl cordon <node>`  manually, but IIUC kubernetes itself can mark a node as unschedulable if e.g. there is no disk space, no memory available..

2022-03-09 08:48 UTC, rccern commented on SwanNotificationsService/swannotificationsservice/service.py
> +        user_pod = self.v1.read_namespaced_pod(f'jupyter-{username}', self.namespace)
true, I don't know how to make it compatible with named servers... in the browser we don't have this info

2022-03-09 08:48 UTC, rccern commented on SwanNotificationsService/swannotificationsservice/app.py
> +            (r'.*', SwanNotificationsService,
we don't, I'll remove it

2022-03-09 11:25 UTC, diocas commented on SwanNotificationsService/swannotificationsservice/service.py
> +        if self.v1.read_node(user_node).spec.unschedulable:
We overcommit for memory, right? So, it would not be possible to add another pod there which is fine. But what happens - if there is no more memory in a node - to the running pods? Would we need to tell them that the node is going to be rebooted?

2022-03-09 11:26 UTC, diocas commented on SwanNotificationsService/swannotificationsservice/service.py
> +        user_pod = self.v1.read_namespaced_pod(f'jupyter-{username}', self.namespace)
No, but we need to add. Unless we send the same message to all of the user containers saying smth like "careful, your session  named X is in a node that's going to be rebooted". In this case this py code need to check for all containers of the user, not just the default.

2022-03-09 12:12 UTC, rccern commented on SwanNotificationsService/swannotificationsservice/service.py
> +        user_pod = self.v1.read_namespaced_pod(f'jupyter-{username}', self.namespace)
ok i'll leave that for another pr

2022-03-09 12:17 UTC, rccern commented on SwanNotificationsService/swannotificationsservice/service.py
> +        if self.v1.read_node(user_node).spec.unschedulable:
If the node is unschedulable there is for sure an issue with the node, so I think we can always notify the user

2022-03-09 13:54 UTC, diocas commented on SwanNotificationsService/Dockerfile
> +FROM gitlab-registry.cern.ch/linuxsupport/cs9-base:20220301-1.x86_64
`python:3.9-alpine`? Sometime alpine versions are not recommended, but this is such a small/simple thing that I would expect it to work.

2022-03-09 13:56 UTC, diocas commented
@rccern how do we automate the publishing and versioning of this?

2022-03-10 07:32 UTC, rccern commented on SwanNotificationsService/Dockerfile
> +FROM gitlab-registry.cern.ch/linuxsupport/cs9-base:20220301-1.x86_64
with alpine it doesn't work, with `python:3.9` it's twice the size than with cs9, i'm leaving cs9

2022-03-10 07:47 UTC, rccern commented
we don't automate this, i don't think we will do this many times. I added a few lines in the README on how to build and push images

if you want to take care of this, please open a new PR

2022-03-14 08:22 UTC, diocas approved these changes

2022-03-14 08:23 UTC, merged