Changes to the web form template related to Alma9
swan-cern/jupyterhub-extensions pull request #88
Opened 2024-01-10 21:43 UTC by etejedor

This PR adds:
- A message to the form to advertise the Alma9 platform and JupyterLab.
- The automatic disabling of the Spark cluster if the selected platform is Alma9 (see commit message for details on why).

2024-01-10 23:38 UTC, PMax5 submitted a review, later dismissed

2024-01-11 08:51 UTC, diocas requested changes

2024-01-11 08:51 UTC, diocas commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +        var selectPlatform = document.getElementById('platformOptions');
```js
var platformOptions = document.getElementById('platformOptions');
var clusterOptions  = document.getElementById('clusterOptions');

var isAlma = platformOptions.selectedOptions[0].text.startsWith('AlmaLinux 9');
clusterOptions.disabled = !isAlma;

if (isAlma) {
    clusterOptions.selectedIndex = 0;
}
```

Our selects only allow single selections, so I would say it's safe to pick the option `[0]`, as the array will always have 1 element.
And I would simplify the rest: if you pick Alma, the Spark Cluster selection changes to None and gets disabled.

2024-01-11 13:24 UTC, etejedor commented on SwanSpawner/swanspawner/templates/options_form_template.html
> +        selectCluster.removeAttribute('disabled');
Please check the new version @diocas . I also had to add this line to make sure the Spark selectable is enabled when switching lcg stack.

2024-01-12 15:19 UTC, diocas approved these changes

2024-01-12 15:20 UTC, merged